version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8010 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8010:8010"
    environment:
      DATABASE_URL: postgresql://fastapi_user:password123@db:5432/fastapi_db
    depends_on:
      - db

volumes:
  db_data:
